package com.example.demo.domain;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import java.time.LocalDateTime;
import java.util.Map;

@Entity
public class Report {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotNull(message = "Report type is required")
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private ReportType reportType;

    @NotNull(message = "Report period is required")
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private ReportPeriod period;

    @NotNull(message = "Generated date is required")
    @PastOrPresent(message = "Generated date cannot be in the future")
    @Column(nullable = false)
    private LocalDateTime generatedDate = LocalDateTime.now();

    @NotNull(message = "Period start date is required")
    @Column(nullable = false)
    private LocalDateTime periodStart;

    @NotNull(message = "Period end date is required")
    @Column(nullable = false)
    private LocalDateTime periodEnd;

    @NotNull(message = "Report data is required")
    @Lob
    @Column(columnDefinition = "TEXT")
    private String reportData; // JSON string containing report data

    @NotBlank(message = "Generated by is required")
    @Size(max = 100, message = "Generated by must be less than 100 characters")
    @Column
    private String generatedBy;

    // Constructors
    public Report() {}

    public Report(ReportType reportType, ReportPeriod period, LocalDateTime periodStart, LocalDateTime periodEnd) {
        this.reportType = reportType;
        this.period = period;
        this.periodStart = periodStart;
        this.periodEnd = periodEnd;
    }

    // Getters and Setters
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public ReportType getReportType() {
        return reportType;
    }

    public void setReportType(ReportType reportType) {
        this.reportType = reportType;
    }

    public ReportPeriod getPeriod() {
        return period;
    }

    public void setPeriod(ReportPeriod period) {
        this.period = period;
    }

    public LocalDateTime getGeneratedDate() {
        return generatedDate;
    }

    public void setGeneratedDate(LocalDateTime generatedDate) {
        this.generatedDate = generatedDate;
    }

    public LocalDateTime getPeriodStart() {
        return periodStart;
    }

    public void setPeriodStart(LocalDateTime periodStart) {
        this.periodStart = periodStart;
    }

    public LocalDateTime getPeriodEnd() {
        return periodEnd;
    }

    public void setPeriodEnd(LocalDateTime periodEnd) {
        this.periodEnd = periodEnd;
    }

    public String getReportData() {
        return reportData;
    }

    public void setReportData(String reportData) {
        this.reportData = reportData;
    }

    public String getGeneratedBy() {
        return generatedBy;
    }

    public void setGeneratedBy(String generatedBy) {
        this.generatedBy = generatedBy;
    }

    @AssertTrue(message = "Period end date must be after period start date")
    private boolean isValidDateRange() {
        if (periodStart == null || periodEnd == null) {
            return true;
        }
        return !periodEnd.isBefore(periodStart);
    }

    // Enums
    public enum ReportType {
        INVENTORY, PAYMENT, SALES
    }

    public enum ReportPeriod {
        DAILY, MONTHLY, YEARLY
    }
}
